development:
  clients:
    default:
      database: mysms_messenger_dev
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 5

test:
  clients:
    default:
      database: mysms_messenger_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      uri: mongodb://host.docker.internal:27017/myapp_production
